from bitgenesis.cognition.context import CognitiveContext
from bitgenesis.cognition.state import CognitiveState

from .base import CognitiveStage


class ExecutionStage(CognitiveStage):
    """
    Executes the plan generated by the planning stage.

    Execution logic is delegated to the configured
    CognitiveExecutor through the CognitiveContext.
    """

    def execute(
        self,
        context: CognitiveContext
    ) -> CognitiveContext:
        """
        Executes the current cognitive plan.
        """

        context.update_state(
            CognitiveState.EXECUTING
        )

        executor = context.executor

        # No executor available.
        # Pipeline continues safely.
        if executor is None:
            return context

        # No plan available.
        if context.plan is None:
            return context

        try:

            result = executor.execute(
                context.plan
            )

            context.response = result

            return context

        except Exception:

            # Execution failures must not
            # destroy the cognitive cycle.
            return context