from bitgenesis.cognition.context import CognitiveContext
from bitgenesis.cognition.state import CognitiveState

from .base import CognitiveStage


class ExecutionStage(CognitiveStage):
    """
    Executes the plan generated by the planning stage.

    Execution results become available to the dialogue
    stage through the cognitive response field.
    """


    def execute(
        self,
        context: CognitiveContext
    ) -> CognitiveContext:


        context.update_state(
            CognitiveState.EXECUTING
        )


        executor = context.executor


        if executor is None:
            return context


        if context.plan is None:
            return context


        try:

            result = executor.execute(
                context.plan
            )


            # Store execution trace
            context.actions.append(
                result
            )


            # Expose execution result
            # to following stages
            context.response = result


            return context


        except Exception as exc:

            context.errors.append(
                str(exc)
            )

            return context