from typing import Any


class CognitiveExecutor:
    """
    Executes cognitive plans produced by the planning stage.

    The executor is intentionally minimal at this layer.
    Concrete implementations can override the execution logic
    for tools, actions, workflows or external systems.
    """

    def execute(self, plan: Any) -> Any:
        """
        Executes a cognitive plan.

        Parameters
        ----------
        plan:
            The plan generated by the planning stage.

        Returns
        -------
        Any
            Execution result.
        """

        return plan