from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, UTC
from typing import Any


@dataclass(slots=True)
class CognitiveResponse:
    """
    Represents the final response generated by the cognitive system.

    A cognitive response is not only textual output,
    but a structured cognitive result containing:

    - generated content
    - confidence evaluation
    - detected intent
    - reasoning trace
    - memory references

    The object keeps compatibility with previous
    string-based response handling.
    """

    # ---------------------------------------------------------
    # Generated content
    # ---------------------------------------------------------

    content: str


    # ---------------------------------------------------------
    # Cognitive metadata
    # ---------------------------------------------------------

    confidence: float = 0.0

    intent: Any = None


    # ---------------------------------------------------------
    # Explainability data
    # ---------------------------------------------------------

    reasoning_trace: list[Any] = field(
        default_factory=list
    )

    memories_used: list[Any] = field(
        default_factory=list
    )


    # ---------------------------------------------------------
    # Runtime metadata
    # ---------------------------------------------------------

    generated_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )


    # ---------------------------------------------------------
    # String compatibility
    # ---------------------------------------------------------

    def __str__(self) -> str:
        """
        Returns the textual response.

        Compatibility with previous behaviour:

            str(response)
        """

        return self.content


    def __eq__(
        self,
        other: object,
    ) -> bool:
        """
        Keeps compatibility with previous string responses.

        Allows:

            response == "text"

        """

        if isinstance(other, str):

            return self.content == other


        if isinstance(other, CognitiveResponse):

            return (
                self.content == other.content
                and
                self.confidence == other.confidence
                and
                self.intent == other.intent
            )


        return False


    def __contains__(
        self,
        item: str,
    ) -> bool:
        """
        Allows:

            "BitGenesis" in response
        """

        return item in self.content


    def lower(self) -> str:
        """
        Allows:

            response.lower()
        """

        return self.content.lower()


    def upper(self) -> str:
        """
        Allows:

            response.upper()
        """

        return self.content.upper()


    def startswith(
        self,
        prefix: str,
    ) -> bool:
        """
        Allows:

            response.startswith("I")
        """

        return self.content.startswith(prefix)


    def endswith(
        self,
        suffix: str,
    ) -> bool:
        """
        Allows:

            response.endswith(".")
        """

        return self.content.endswith(suffix)


    # ---------------------------------------------------------
    # Serialization
    # ---------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """
        Returns a serializable representation.
        """

        return {
            "content": self.content,
            "confidence": self.confidence,
            "intent": self.intent,
            "reasoning_trace": self.reasoning_trace,
            "memories_used": self.memories_used,
            "generated_at": self.generated_at.isoformat(),
        }