from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, UTC
from typing import Any


@dataclass(slots=True)
class CognitiveResponse:
    """
    Represents the final response generated by the cognitive system.

    A cognitive response is not only textual output,
    but a structured result containing metadata about
    the cognitive process that produced it.

    This structure allows future integration with:

    - reasoning traces
    - memory references
    - confidence evaluation
    - learning feedback
    - self evaluation
    """

    # ---------------------------------------------------------
    # Generated content
    # ---------------------------------------------------------

    content: str


    # ---------------------------------------------------------
    # Cognitive metadata
    # ---------------------------------------------------------

    confidence: float = 0.0

    intent: Any = None


    # ---------------------------------------------------------
    # Explainability data
    # ---------------------------------------------------------

    reasoning_trace: list[Any] = field(
        default_factory=list
    )

    memories_used: list[Any] = field(
        default_factory=list
    )


    # ---------------------------------------------------------
    # Runtime metadata
    # ---------------------------------------------------------

    generated_at: datetime = field(
        default_factory=lambda: datetime.now(UTC)
    )


    # ---------------------------------------------------------
    # Helpers
    # ---------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """
        Returns a serializable representation.
        """

        return {
            "content": self.content,
            "confidence": self.confidence,
            "intent": self.intent,
            "reasoning_trace": self.reasoning_trace,
            "memories_used": self.memories_used,
            "generated_at": self.generated_at.isoformat(),
        }